In [2]:
import pandas as pd

In [3]:
import pandas as pd

movies = pd.read_csv(r"C:\Users\naina\Downloads\ml-latest-small\ml-latest-small\movies.csv")
ratings = pd.read_csv(r"C:\Users\naina\Downloads\ml-latest-small\ml-latest-small\ratings.csv")
tags = pd.read_csv(r"C:\Users\naina\Downloads\ml-latest-small\ml-latest-small\tags.csv")
links = pd.read_csv(r"C:\Users\naina\Downloads\ml-latest-small\ml-latest-small\links.csv")

In [4]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
print("Movies:", movies.shape)
print("Ratings:", ratings.shape)
print("Tags:", tags.shape)
print("Links:", links.shape)

Movies: (9742, 3)
Ratings: (100836, 4)
Tags: (3683, 4)
Links: (9742, 3)

In [6]:
print("Movies Columns:", movies.columns)
print("Ratings Columns:", ratings.columns)
print("Tags Columns:", tags.columns)
print("Links Columns:", links.columns)

Movies Columns: Index(['movieId', 'title', 'genres'], dtype='object')
Ratings Columns: Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')
Tags Columns: Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')
Links Columns: Index(['movieId', 'imdbId', 'tmdbId'], dtype='object')

In [7]:
print("Movies Data Types:")
print(movies.dtypes)

print("\nRatings Data Types:")
print(ratings.dtypes)

print("\nTags Data Types:")
print(tags.dtypes)

print("\nLinks Data Types:")
print(links.dtypes)

Movies Data Types:
movieId     int64
title      object
genres     object
dtype: object

Ratings Data Types:
userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

Tags Data Types:
userId        int64
movieId       int64
tag          object
timestamp     int64
dtype: object

Links Data Types:
movieId      int64
imdbId       int64
tmdbId     float64
dtype: object

In [8]:
print("Movies:")
print(movies.isnull().sum())

print("\nRatings:")
print(ratings.isnull().sum())

print("\nTags:")
print(tags.isnull().sum())

print("\nLinks:")
print(links.isnull().sum())

Movies:
movieId    0
title      0
genres     0
dtype: int64

Ratings:
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

Tags:
userId       0
movieId      0
tag          0
timestamp    0
dtype: int64

Links:
movieId    0
imdbId     0
tmdbId     8
dtype: int64

In [9]:
print("Movies Duplicates:", movies.duplicated().sum())
print("Ratings Duplicates:", ratings.duplicated().sum())
print("Tags Duplicates:", tags.duplicated().sum())
print("Links Duplicates:", links.duplicated().sum())

Movies Duplicates: 0
Ratings Duplicates: 0
Tags Duplicates: 0
Links Duplicates: 0

In [10]:
print(ratings.describe())

              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [11]:
print("Number of Unique Users:", ratings["userId"].nunique())
print("Number of Unique Movies:", movies["movieId"].nunique())

Number of Unique Users: 610
Number of Unique Movies: 9742

In [12]:
print(ratings["rating"].value_counts().sort_index())

rating
0.5     1370
1.0     2811
1.5     1791
2.0     7551
2.5     5550
3.0    20047
3.5    13136
4.0    26818
4.5     8551
5.0    13211
Name: count, dtype: int64

In [13]:
print("Common column between all datasets: movieId")
print("movies.csv + ratings.csv -> movieId")
print("movies.csv + tags.csv -> movieId")
print("movies.csv + links.csv -> movieId")
print("ratings.csv + tags.csv -> userId and movieId")

Common column between all datasets: movieId
movies.csv + ratings.csv -> movieId
movies.csv + tags.csv -> movieId
movies.csv + links.csv -> movieId
ratings.csv + tags.csv -> userId and movieId

Day-3: Data Preprocessing

In [14]:
master_df = ratings.merge(movies, on="movieId", how="left")
master_df = master_df.merge(links, on="movieId", how="left")
master_df = master_df.merge(tags, on=["userId", "movieId"], how="left")
master_df.head()

,userId,movieId,rating,timestamp_x,title,genres,imdbId,tmdbId,tag,timestamp_y
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,NaN,NaN
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance,113228,15602.0,NaN,NaN
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller,113277,949.0,NaN,NaN
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,114369,807.0,NaN,NaN
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,114814,629.0,NaN,NaN

In [15]:
print("Duplicate rows before:", master_df.duplicated().sum())
master_df = master_df.drop_duplicates()
print("Duplicate rows after:", master_df.duplicated().sum())

Duplicate rows before: 0
Duplicate rows after: 0

In [16]:
print(master_df.isnull().sum())

userId             0
movieId            0
rating             0
timestamp_x        0
title              0
genres             0
imdbId             0
tmdbId            13
tag            99201
timestamp_y    99201
dtype: int64

In [17]:
master_df["tag"] = master_df["tag"].fillna("No Tag")
master_df = master_df.dropna(subset=["tmdbId"])
master_df.isnull().sum()

userId             0
movieId            0
rating             0
timestamp_x        0
title              0
genres             0
imdbId             0
tmdbId             0
tag                0
timestamp_y    99188
dtype: int64

In [18]:
master_df["timestamp_y"] = master_df["timestamp_y"].fillna(0)
master_df.isnull().sum()

userId         0
movieId        0
rating         0
timestamp_x    0
title          0
genres         0
imdbId         0
tmdbId         0
tag            0
timestamp_y    0
dtype: int64

In [19]:
master_df["timestamp_x"] = pd.to_datetime(master_df["timestamp_x"], unit="s")
master_df["timestamp_y"] = pd.to_datetime(master_df["timestamp_y"], unit="s")
master_df.dtypes

userId                  int64
movieId                 int64
rating                float64
timestamp_x    datetime64[ns]
title                  object
genres                 object
imdbId                  int64
tmdbId                float64
tag                    object
timestamp_y    datetime64[ns]
dtype: object

Feature Exploration

In [20]:
print("Total Movies:", master_df["movieId"].nunique())
print("Total Users:", master_df["userId"].nunique())
print("Total Ratings:", len(master_df))
print("\nTop 10 Most Rated Movies:")
print(master_df["title"].value_counts().head(10))
average_ratings = master_df.groupby("title")["rating"].mean().sort_values(ascending=False)
print("\nAverage Rating of Each Movie:")
print(average_ratings.head(10))
movie_stats = master_df.groupby("title").agg(
    average_rating=("rating", "mean"),
    total_ratings=("rating", "count")
)
top_movies = movie_stats[movie_stats["total_ratings"] >= 50].sort_values(
    by="average_rating",
    ascending=False
)
print("\nHighest Average Rated Movies (Minimum 50 Ratings):")
print(top_movies.head(10))
print("\nGenre Distribution:")
genre_distribution = master_df["genres"].str.split("|").explode().value_counts()
print(genre_distribution)

Total Movies: 9716
Total Users: 610
Total Ratings: 102664

Top 10 Most Rated Movies:
title
Pulp Fiction (1994)                          484
Forrest Gump (1994)                          335
Shawshank Redemption, The (1994)             319
Silence of the Lambs, The (1991)             283
Matrix, The (1999)                           280
Fight Club (1999)                            268
Star Wars: Episode IV - A New Hope (1977)    262
Braveheart (1995)                            245
Jurassic Park (1993)                         238
Terminator 2: Judgment Day (1991)            229
Name: count, dtype: int64

Average Rating of Each Movie:
title
Ballad of Narayama, The (Narayama bushiko) (1983)    5.0
Story of Women (Affaire de femmes, Une) (1988)       5.0
12 Angry Men (1997)                                  5.0
12 Chairs (1976)                                     5.0
Ex Drummer (2007)                                    5.0
'Salem's Lot (2004)                                  5.0
Supercop 2 (Project S) (Chao ji ji hua) (1993)       5.0
Superman/Batman: Public Enemies (2009)               5.0
Wow! A Talking Fish! (1983)                          5.0
Death Note: Desu nôto (2006–2007)                    5.0
Name: rating, dtype: float64

Highest Average Rated Movies (Minimum 50 Ratings):
                                                    average_rating  \
title
Pulp Fiction (1994)                                       4.487603
Shawshank Redemption, The (1994)                          4.432602
Fight Club (1999)                                         4.402985
Godfather, The (1972)                                     4.289062
Eternal Sunshine of the Spotless Mind (2004)              4.278481
Cool Hand Luke (1967)                                     4.271930
Godfather: Part II, The (1974)                            4.265385
Dr. Strangelove or: How I Learned to Stop Worry...        4.264706
Departed, The (2006)                                      4.254386
Usual Suspects, The (1995)                                4.252404

                                                    total_ratings
title
Pulp Fiction (1994)                                           484
Shawshank Redemption, The (1994)                              319
Fight Club (1999)                                             268
Godfather, The (1972)                                         192
Eternal Sunshine of the Spotless Mind (2004)                  158
Cool Hand Luke (1967)                                          57
Godfather: Part II, The (1974)                                130
Dr. Strangelove or: How I Learned to Stop Worry...            102
Departed, The (2006)                                          114
Usual Suspects, The (1995)                                    208

Genre Distribution:
genres
Drama                 43022
Comedy                39619
Action                31151
Thriller              27171
Adventure             24493
Romance               18352
Sci-Fi                17684
Crime                 17222
Fantasy               11989
Children               9285
Mystery                7905
Horror                 7407
Animation              7119
War                    4931
IMAX                   4258
Musical                4170
Western                1966
Documentary            1258
Film-Noir               880
(no genres listed)       49
Name: count, dtype: int64

Feature Engineering

In [21]:
master_df["year"] = master_df["title"].str.extract(r"\((\d{4})\)")
master_df["year"] = pd.to_numeric(master_df["year"], errors="coerce")
master_df["primary_genre"] = master_df["genres"].str.split("|").str[0]
movie_rating_count = master_df.groupby("movieId")["rating"].count().reset_index()
movie_rating_count.rename(columns={"rating": "rating_count"}, inplace=True)
master_df = master_df.merge(movie_rating_count, on="movieId", how="left")
master_df.head()

,userId,movieId,rating,timestamp_x,title,genres,imdbId,tmdbId,tag,timestamp_y,year,primary_genre,rating_count
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,No Tag,1970-01-01,1995.0,Adventure,215
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,113228,15602.0,No Tag,1970-01-01,1995.0,Comedy,53
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,113277,949.0,No Tag,1970-01-01,1995.0,Action,102
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,114369,807.0,No Tag,1970-01-01,1995.0,Mystery,204
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,114814,629.0,No Tag,1970-01-01,1995.0,Crime,208

In [22]:
interaction_matrix = master_df.pivot_table(
    index="userId",
    columns="movieId",
    values="rating"
)
interaction_matrix.head()

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
master_df.to_csv("master_dataset.csv", index=False)
interaction_matrix.to_csv("user_movie_matrix.csv")
print("Files saved successfully!")

Files saved successfully!